# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --max-complexity=10 --max-line-length=127
    - name: Verify sorted imports
      run: |
        isort . -m HANGING_INDENT -l 120 --check-only
    - name: Test installation
      run: |
        python3 -m pip install .
    - name: Test usage
      run: |
        python3 -m pyipsw
